--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "ELIBRARY"."ADMIN" 
   (	"ADMIN_ID" NUMBER, 
	"ADMIN_USER_ID" VARCHAR2(40 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"EMAIL_ID" VARCHAR2(40 BYTE), 
	"DOB" DATE, 
	"MOBILE" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELIBRARY"."ADMIN_PK" ON "ELIBRARY"."ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "ELIBRARY"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ELIBRARY"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "ELIBRARY"."BOOK" 
   (	"BOOK_ID" NUMBER, 
	"CALL_NO" VARCHAR2(20 BYTE), 
	"BOOK_NAME" VARCHAR2(80 BYTE), 
	"AUTHOR_NAME" VARCHAR2(40 BYTE), 
	"PUBLISHER" VARCHAR2(40 BYTE), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELIBRARY"."BOOK_PK" ON "ELIBRARY"."BOOK" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "ELIBRARY"."BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ELIBRARY"."BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table LIBRARIAN
--------------------------------------------------------

  CREATE TABLE "ELIBRARY"."LIBRARIAN" 
   (	"LIBRARIAN_ID" NUMBER, 
	"LIBRARIAN_USER_ID" VARCHAR2(40 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"EMAIL_ID" VARCHAR2(40 BYTE), 
	"DOB" DATE, 
	"MOBILE" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIBRARIAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELIBRARY"."LIBRARIAN_PK" ON "ELIBRARY"."LIBRARIAN" ("LIBRARIAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LIBRARIAN
--------------------------------------------------------

  ALTER TABLE "ELIBRARY"."LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_PK" PRIMARY KEY ("LIBRARIAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ELIBRARY"."LIBRARIAN" MODIFY ("LIBRARIAN_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "ELIBRARY"."STUDENT" 
   (	"STUDENT_ID" NUMBER, 
	"STUDENT_USER_ID" VARCHAR2(40 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"EMAIL_ID" VARCHAR2(40 BYTE), 
	"DOB" DATE, 
	"MOBILE" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELIBRARY"."STUDENT_PK" ON "ELIBRARY"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "ELIBRARY"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ELIBRARY"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table STUDENT_BOOK
--------------------------------------------------------

  CREATE TABLE "ELIBRARY"."STUDENT_BOOK" 
   (	"STUDENT_BOOK_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"ISSUE_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"RETURN_STATUS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELIBRARY"."STUDENT_BOOK_PK" ON "ELIBRARY"."STUDENT_BOOK" ("STUDENT_BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT_BOOK
--------------------------------------------------------

  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_CHK1" CHECK (RETURN_STATUS = 'Y' OR RETURN_STATUS = 'N') ENABLE;
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_PK" PRIMARY KEY ("STUDENT_BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" MODIFY ("RETURN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" MODIFY ("RETURN_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" MODIFY ("STUDENT_BOOK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_BOOK
--------------------------------------------------------

  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_FK1" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "ELIBRARY"."STUDENT" ("STUDENT_ID") ENABLE;
  ALTER TABLE "ELIBRARY"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_FK2" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "ELIBRARY"."BOOK" ("BOOK_ID") ENABLE;


--------------------------------------------------------
--  DDL for Sequence ADMIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ELIBRARY"."ADMIN_SEQ"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
   
   --------------------------------------------------------
--  DDL for Sequence BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ELIBRARY"."BOOK_SEQ"  MINVALUE 1000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
   
   --------------------------------------------------------
--  DDL for Sequence STUDENT_BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ELIBRARY"."STUDENT_BOOK_SEQ"  MINVALUE 1000 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
   
   --------------------------------------------------------
--  DDL for Sequence STUDENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ELIBRARY"."STUDENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;







